import { Scale } from "./Scale";
import { Position } from "./Position";
import { Rotation } from "./Rotation";

export interface PlacementData {
    placementDataId?: number; // optional, generated by backend
    scale: Scale;              // use Scale from Scale.ts
    position: Position;        // use Position from Position.ts
    rotation: Rotation;        // use Rotation from Rotation.ts
}
